### ISSUE TITLE
Mch lines wrong color in kyitrai theme

### ISSUE THREAD

**Issue by Ecliptix** [billyvg/OverlayPlugin-themes#11]
Missing a comma on line 153:

`--- kyitrai.html        2015-08-26 10:39:09.000000000 -0700`
`+++ kyitrai.html.new    2015-12-15 22:04:31.254151977 -0700`
`@@ -153 +153 @@`
`-        .job-Lnc div.bar,    .job-Pgl div.bar,    .job-Rog div.bar,    .job-Thm div.bar,    .job-Arc div.bar,    .job-Acn div.bar`
`+        .job-Lnc div.bar,    .job-Pgl div.bar,    .job-Rog div.bar,    .job-Thm div.bar,    .job-Arc div.bar,    .job-Acn div.bar,`

**Comment by ezsoftware** [comment]
fix included with pull request "Missing Job Icons and SB support for RainbowMage based themes #19"
