### ISSUE TITLE
Help updating with new classes

### ISSUE THREAD

**Issue by jquick** [billyvg/OverlayPlugin-themes#3]
Hey, love your parser theme (rdmty_default.html). Was wondering if you would mind updating for the 3 new classes or giving a brief overview of what I need to add to get it working. 

Thanks!

**Comment by billyvg** [comment]
Yeah I'll update it sometime this week, do you know where I can find the new job icons?

**Comment by jquick** [comment]
http://b.thumbs.redditmedia.com/E_5vndu5_BTtNVBXgfgJGLsthvFZSZ6YfOtcGfgGubk.png

Right 3

**Comment by Zythrawl** [comment]
Yeah I also need the updated job icons. Your theme is the best one out of all of them imo. The only problem I have is that the numbers are a lot more than what is shown on the actual ACT window for some reason, don't know if it's just me but yeah.

**Comment by billyvg** [comment]
Fixed in ddf79f7f64f3b37aefd6b0c81abac21c51964044

@Zythrawl That's a known problem, I'll look into it..

**Comment by billyvg** [comment]
@Zythrawl DPS is fixed now, was using the wrong property
