### ISSUE TITLE
Layout broken for most overlays

### ISSUE THREAD

**Issue by Zireael** [billyvg/OverlayPlugin-themes#6]
Some overlays are broken for me, with layout being messed up. See screenshots for examples. I've had this before reinstalling Windows to current version, just decided to report now.
I use Win 7 x64 EN.

![9](https://cloud.githubusercontent.com/assets/3856578/8760056/cff7cbb8-2cff-11e5-8223-4a0b930fbd55.png)
![1](https://cloud.githubusercontent.com/assets/3856578/8760058/cffd380a-2cff-11e5-809f-23025fe1a079.png)
![2](https://cloud.githubusercontent.com/assets/3856578/8760057/cffc8a2c-2cff-11e5-923c-c90dde95fe88.png)
![3](https://cloud.githubusercontent.com/assets/3856578/8760061/d005bc82-2cff-11e5-8e89-40ec997bc6b0.png)
![4](https://cloud.githubusercontent.com/assets/3856578/8760060/d00273ce-2cff-11e5-8559-20cba74827c7.png)
![5](https://cloud.githubusercontent.com/assets/3856578/8760059/cfffc3cc-2cff-11e5-8634-14b3972ce35c.png)
![6](https://cloud.githubusercontent.com/assets/3856578/8760062/d00fddb6-2cff-11e5-8dd6-7ae7f5c7ad86.png)
![7](https://cloud.githubusercontent.com/assets/3856578/8760064/d0182372-2cff-11e5-9a96-07778e40f044.png)
![8](https://cloud.githubusercontent.com/assets/3856578/8760063/d017be82-2cff-11e5-9bc8-4a00b8b1c6dd.png)

**Comment by Mike-Sinistralis** [comment]
Is this as simple as your window is too small?

**Comment by christianallred** [comment]
I am going to close this out as most overlays are going to be getting updated in the comings weeks
